name: face-recognition
channels:
  - defaults
  - conda-forge
  - pytorch
dependencies:
  - python=3.10
  - pip
  - pytorch
  - torchvision
  - faiss-cpu
  - pip:
      - streamlit
      - pillow
      - numpy
