name: face-recognition
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - numpy
  - faiss-cpu
  - pip:
      - torch==2.2.2+cu118
      - torchvision==0.17.2+cu118
      - pillow
      - streamlit
      - scikit-learn
      - matplotlib
      - tqdm
      - kagglehub
      - facenet_pytorch
      - insightface 
      - keras-vggface 
      - keras 
      - tensorflow
        